# Generated by Django 5.0.6 on 2024-11-08 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asignatura', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jornada', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sala', models.CharField(max_length=100)),
                ('piso_sala', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_seccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AsignaturaSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ionic.asignatura')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ionic.jornada')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ionic.profesor')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ionic.sala')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ionic.seccion')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ionic.carrera'),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ionic.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_clase', models.DateField()),
                ('asignatura_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ionic.asignaturaseccion')),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ionic.asignaturaseccion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ionic.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_asistencia', models.TimeField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ionic.estadoasistencia')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ionic.estudiante')),
                ('horario_clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ionic.horarioclase')),
            ],
        ),
    ]
