# Generated by Django 5.0.6 on 2024-11-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_ionic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='asignatura',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='nombre',
            field=models.CharField(default='Nombre por defecto', max_length=100),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='sala',
            field=models.CharField(default='sala por defecto', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asistencia',
            name='seccion',
            field=models.CharField(default='seccion por defecto', max_length=5),
            preserve_default=False,
        ),
    ]
